name: Build and Release Executable

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. V1.2.3)"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller main.spec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          files: dist/haversine.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
